fix mono palette
regression started since 'urwid-2.6.14'

```
urwid.display.common.AttrSpecError: foreground/background ('white'/'default') require more colors than have been specified (1).
```
'white' is no longer valid, had to switch to 'bold'

Fixes #179

Signed-off-by: Tomas Tomecek <ttomecek@redhat.com>