follow logs: display whole lines properly
docker sends every character, instead of whole lines

needs testing on 1.8 and 1.9 this works on 1.10

1.10 sends this:

11:22:57 sen.tui.widgets.list.common DEBUG  ' '
11:22:57 sen.tui.widgets.list.common DEBUG  'H'
11:22:57 sen.tui.widgets.list.common DEBUG  'T'
11:22:57 sen.tui.widgets.list.common DEBUG  'T'
11:22:57 sen.tui.widgets.list.common DEBUG  'P'
11:22:57 sen.tui.widgets.list.common DEBUG  '/'
11:22:57 sen.tui.widgets.list.common DEBUG  '1'
11:22:57 sen.tui.widgets.list.common DEBUG  '.'
11:22:57 sen.tui.widgets.list.common DEBUG  '1'
11:22:57 sen.tui.widgets.list.common DEBUG  '"'
11:22:57 sen.tui.widgets.list.common DEBUG  ' '
11:22:57 sen.tui.widgets.list.common DEBUG  '2'
11:22:57 sen.tui.widgets.list.common DEBUG  '0'
11:22:57 sen.tui.widgets.list.common DEBUG  '0'
11:22:57 sen.tui.widgets.list.common DEBUG  ' '
11:22:57 sen.tui.widgets.list.common DEBUG  '-'
11:22:57 sen.tui.widgets.list.common DEBUG  '\r'
11:22:57 sen.tui.widgets.list.common DEBUG  '\n'

+ there is also a timeout:

Traceback (most recent call last):
  File "/usr/lib64/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tt/g/sen/sen/tui/widgets/list/common.py", line 43, in fetch_logs
    for line in generator:
  File "/home/tt/.local/lib/python3.5/site-packages/docker/client.py", line 279, in _stream_raw_result
    for out in response.iter_content(chunk_size=1, decode_unicode=True):
  File "/usr/lib/python3.5/site-packages/requests/utils.py", line 363, in stream_decode_response_unicode
    for chunk in iterator:
  File "/usr/lib/python3.5/site-packages/requests/models.py", line 667, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out.